/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author nenis
 */
public class InterfazInicio extends javax.swing.JFrame {

    /**
     * Creates new form InterfazInicio
     */
    public InterfazInicio() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("PLACES TEC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnRutaViaje = new javax.swing.JButton();
        BtnSitiosInteres = new javax.swing.JButton();
        BtnLugaresDestino = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(645, 455));
        getContentPane().setLayout(null);

        BtnRutaViaje.setBackground(new java.awt.Color(255, 255, 255));
        BtnRutaViaje.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnRutaViaje.setText("Armar Ruta de Viaje");
        BtnRutaViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRutaViajeActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRutaViaje);
        BtnRutaViaje.setBounds(380, 360, 230, 31);

        BtnSitiosInteres.setBackground(new java.awt.Color(255, 255, 255));
        BtnSitiosInteres.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnSitiosInteres.setText("Sitios de Interés Cercanos");
        BtnSitiosInteres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSitiosInteresActionPerformed(evt);
            }
        });
        getContentPane().add(BtnSitiosInteres);
        BtnSitiosInteres.setBounds(380, 300, 230, 31);

        BtnLugaresDestino.setBackground(new java.awt.Color(255, 255, 255));
        BtnLugaresDestino.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        BtnLugaresDestino.setText("Gestionar Lugares Destino");
        BtnLugaresDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLugaresDestinoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLugaresDestino);
        BtnLugaresDestino.setBounds(380, 240, 230, 31);

        jLabel3.setFont(new java.awt.Font("Papyrus", 1, 36)); // NOI18N
        jLabel3.setText("PLACES TEC");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 40, 350, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("¿Qué desea hacer?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 140, 310, 50);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\nenis\\Desktop\\viajar-2.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnLugaresDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLugaresDestinoActionPerformed
        VentanaDestinos obj = new VentanaDestinos();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnLugaresDestinoActionPerformed

    private void BtnSitiosInteresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSitiosInteresActionPerformed
        VentanaSitiosInteres obj = new VentanaSitiosInteres();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnSitiosInteresActionPerformed

    private void BtnRutaViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRutaViajeActionPerformed
       VentanaRutaViaje obj = new VentanaRutaViaje();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_BtnRutaViajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLugaresDestino;
    private javax.swing.JButton BtnRutaViaje;
    private javax.swing.JButton BtnSitiosInteres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
